# Generated by Django 5.1.6 on 2025-02-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Kérdés')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('DATE', 'Date Input'), ('STRING', 'String Matching')], default='MC', max_length=10, verbose_name='Kérdés típusa')),
                ('option_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='Válasz A')),
                ('option_b', models.CharField(blank=True, max_length=200, null=True, verbose_name='Válasz B')),
                ('option_c', models.CharField(blank=True, max_length=200, null=True, verbose_name='Válasz C')),
                ('option_d', models.CharField(blank=True, max_length=200, null=True, verbose_name='Válasz D')),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Helyes válasz (MC)')),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Helyes válasz (szöveg)')),
                ('times_asked', models.IntegerField(default=0, verbose_name='Futtatások száma')),
                ('times_correct', models.IntegerField(default=0, verbose_name='Helyes válaszok száma')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Felhasználó')),
                ('user_answer', models.CharField(max_length=200, verbose_name='Felhasználó válasza')),
                ('correct_option', models.CharField(blank=True, max_length=200, null=True, verbose_name='Helyes válasz')),
                ('score', models.FloatField(default=0, verbose_name='Pontszám')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Időbélyeg')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Kérdés')),
            ],
            options={
                'db_table': 'quiz_attempt',
            },
        ),
    ]
